data_config:
  enable_query_instruct: true
  hard_neg_num: 0
  image_size: 224, 224
  in_batch_neg_num: 0
  query_instruct_path: instructions/query_instructions.tsv
  returns: null
  shuffle_cand: true
  train_cand_pool_path: cand_pool/global/mbeir_union_train_cand_pool.jsonl
  train_query_data_path: query/union_train/mbeir_union_up_train.jsonl
  val_cand_pool_path: cand_pool/global/mbeir_union_val_cand_pool.jsonl
  val_query_data_path: query/union_val/mbeir_union_val.jsonl
dataloader_config:
  num_workers: 2
  train_batch_size: 4
  valid_batch_size: 20
dist_config:
  dist_url: env://
evaluator:
  enable_eval: false
  eval_freq: 1
  print_freq: 10
experiment:
  description: ${model.name} ${model.size} ${experiment.instruct_status} ${experiment.exp_name}
  exp_name: InBatch
  instruct_status: Instruct
  path_suffix: ${model.short_name}/${model.size}/${experiment.instruct_status}/${experiment.exp_name}/
logger_config:
  logger_out_dir: logger/${experiment.path_suffix}
  logger_out_file_name: train.log
model:
  align_vision_model_name: temp
  ckpt_config:
    ckpt_dir: checkpoint/${experiment.path_suffix}
    ckpt_name: ''
    resume_training: false
  gather_embeddings: true
  name: ALIGNScoreFusion
  pretrained_align_model_dir: checkpoint/ALIGN/
  short_name: ALIGN_SF
  size: Large
seed: 2023
trainer_config:
  eval_steps: 500
  gradient_accumulation_steps: 1
  learning_rate: 1e-5
  num_train_epochs: 20
  print_freq: 50
  warmup_steps: 0
wandb_config:
  enabled: true
  experiment_name: ${experiment.description}
